### ISSUE TITLE
How to make model file....

### ISSUE THREAD

**Issue by NTS-SW** [WhiteKIM/fireAlarmService#1]
Hello.

I would like to ask you to how to make model files. 
what kind of dataset do you use to make model? 

thanks in advance.

**Comment by WhiteKIM** [comment]
i use this (https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100), but my model train not enough, and if you want to make model, use train.py show this link you can more understand (https://github.com/WongKinYiu/yolov7)
