### ISSUE TITLE
question about your model... bestofbest.pt

### ISSUE THREAD

**Issue by NTS-SW** [WhiteKIM/fireAlarmService#2]
Hello

I downloaded your prebuilt model and try to test that with fire-movie file/.
But I can't no one.... 

What is your yolov7 model? yolov7 or yolov7x ? 
What is your input images size, 640x640? 

Thank you inadvance//

**Comment by WhiteKIM** [comment]
@NTS-SW I use this
model file : yolov7.yaml
and i think, i am not set any input size. So, input size set default size 640x640

**Comment by NTS-SW** [comment]
@WhiteKIM 
Hm....

I think the model file size(about 290MB) is too big for yolo7.yaml.
A Default model size for yolo7.yaml in official site is about 72 MB.

**Comment by NTS-SW** [comment]
@WhiteKIM 

Could you share your test video file in your site and youtube? 

Project.avi is not the same that you show us.

**Comment by WhiteKIM** [comment]
@NTS-SW sorry. I am missing my original test video file.
